"""
Script 6: Mutual information analysis — circularity quantification.

Computes normalized mutual information I(feature; target) / H(target) between
each physics-derived feature and each prediction target on the training split.

Rationale [buggineni2024synthetic, willard2020integrating]:
  Since targets are generated by a physics model and features are computed from
  related (but not identical) physics equations, some association is expected and
  desirable. This script quantifies the degree of residual association after the
  two-tier physics separation implemented in generate_bof_data.py.

  Interpretation of NMI values:
    < 0.30 : low association — feature provides general physical context
    0.30–0.60 : moderate association — feature informative but not deterministic
    0.60–0.85 : high association — strong structural link to target
    > 0.85 : near-deterministic — potential residual circularity

Outputs:
  results/mutual_info.csv          : NMI per (feature, target)
  Images/results/mi_heatmap.pdf    : heatmap of NMI values
"""

import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_selection import mutual_info_regression
from sklearn.preprocessing import StandardScaler

from scripts.utils.physics import RAW_FEATURES

PHYSICS_FEATURES = [
    'theo_o2_demand', 'o2_efficiency', 'enthalpy_surplus',
    'total_oxidized_mass', 'decarb_rate', 'slag_basicity',
    'scrap_melt_capacity', 'fe_oxidation_loss',
]
ALL_FEATURES = RAW_FEATURES + PHYSICS_FEATURES
TARGETS = ['T_final', 'C_final', 'P_final']
N_NEIGHBORS = 5   # k for MI estimation [kraskov2004estimating]
SEED = 42


def entropy_continuous_standardized():
    """
    Differential entropy of a unit-variance Gaussian: H(Y) = 0.5*log(2πe).
    Since mutual_info_regression internally standardizes features and target,
    we normalize MI by the entropy of the standardized target for consistency.
    This ensures NMI values are in [0, 1] range [kraskov2004estimating].
    """
    return float(0.5 * np.log(2 * np.pi * np.e))  # ≈ 1.4189


def compute_nmi(X, y, feature_names, seed=SEED):
    """
    Compute MI(X_i; y) for each feature i, then normalize by H(y_std).
    mutual_info_regression standardizes internally, so we normalize by the
    entropy of a unit-variance Gaussian for scale-consistent NMI in [0,1].
    Returns dict of feature -> NMI.
    """
    mi = mutual_info_regression(X, y, n_neighbors=N_NEIGHBORS, random_state=seed)
    h_y = entropy_continuous_standardized()
    return {fname: round(float(np.clip(mi_val / h_y, 0.0, 1.0)), 4)
            for fname, mi_val in zip(feature_names, mi)}


def main():
    os.makedirs('results', exist_ok=True)
    os.makedirs('Images/results', exist_ok=True)

    phys_path = 'data/features_physics.csv'
    if not os.path.exists(phys_path):
        print(f"ERROR: {phys_path} not found. Run feature_engineering.py first.")
        sys.exit(1)

    df = pd.read_csv(phys_path)
    df_train = df[df['split'] == 'train'].copy()

    scaler = StandardScaler()
    X_all = scaler.fit_transform(df_train[ALL_FEATURES].values)
    X_raw = scaler.fit_transform(df_train[RAW_FEATURES].values)
    X_phys = df_train[PHYSICS_FEATURES].values   # unscaled OK for MI estimation

    rows = []
    nmi_matrix_phys = {}  # feature -> {target -> NMI}
    nmi_matrix_raw  = {}

    print("Computing mutual information (physics features vs targets)...")
    for target in TARGETS:
        y = df_train[target].values

        # Physics-derived features only
        nmi_phys = compute_nmi(X_phys, y, PHYSICS_FEATURES)
        for feat, nmi in nmi_phys.items():
            rows.append({'feature_set': 'physics', 'feature': feat,
                         'target': target, 'NMI': nmi})
            nmi_matrix_phys.setdefault(feat, {})[target] = nmi

        # Raw features (for comparison baseline)
        nmi_raw_vals = compute_nmi(X_raw, y, RAW_FEATURES)
        for feat, nmi in nmi_raw_vals.items():
            rows.append({'feature_set': 'raw', 'feature': feat,
                         'target': target, 'NMI': nmi})
            nmi_matrix_raw.setdefault(feat, {})[target] = nmi

        print(f"\n  {target} — physics features NMI (normalized by H(target)):")
        for feat, nmi in sorted(nmi_phys.items(), key=lambda x: -x[1]):
            flag = ' *** HIGH' if nmi > 0.60 else (' ** MOD' if nmi > 0.30 else '')
            print(f"    {feat:25s}: {nmi:.4f}{flag}")

    df_mi = pd.DataFrame(rows)
    df_mi.to_csv('results/mutual_info.csv', index=False)
    print(f"\nSaved: results/mutual_info.csv")

    # --- Heatmap: physics features NMI ---
    pivot = pd.DataFrame(nmi_matrix_phys).T  # features × targets
    pivot = pivot.reindex(columns=TARGETS)
    pivot = pivot.sort_values(TARGETS[0], ascending=False)

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    sns.heatmap(
        pivot, annot=True, fmt='.3f', cmap='YlOrRd',
        vmin=0.0, vmax=1.0, ax=axes[0], linewidths=0.5,
        cbar_kws={'label': 'NMI = I(f;y)/H(y)'}
    )
    axes[0].set_title('Informação Mútua Normalizada\n(Atributos Físico-Derivados × Alvos)',
                      fontsize=11)
    axes[0].set_xlabel('Alvo', fontsize=10)
    axes[0].set_ylabel('Atributo', fontsize=10)

    # Also show top raw features for context
    pivot_raw = pd.DataFrame(nmi_matrix_raw).T.reindex(columns=TARGETS)
    pivot_raw = pivot_raw.sort_values(TARGETS[0], ascending=False).head(8)
    sns.heatmap(
        pivot_raw, annot=True, fmt='.3f', cmap='Blues',
        vmin=0.0, vmax=1.0, ax=axes[1], linewidths=0.5,
        cbar_kws={'label': 'NMI'}
    )
    axes[1].set_title('NMI — Top 8 Atributos Brutos\n(referência comparativa)',
                      fontsize=11)
    axes[1].set_xlabel('Alvo', fontsize=10)
    axes[1].set_ylabel('Atributo', fontsize=10)

    plt.tight_layout()
    out = 'Images/results/mi_heatmap.pdf'
    plt.savefig(out, bbox_inches='tight')
    plt.close()
    print(f"Saved: {out}")

    # Summary: any NMI > 0.85 (residual circularity warning)?
    high = df_mi[(df_mi['feature_set'] == 'physics') & (df_mi['NMI'] > 0.85)]
    if high.empty:
        print("\nCircularity check: no physics feature has NMI > 0.85 — two-tier separation effective.")
    else:
        print("\nCircularity WARNING — features with NMI > 0.85:")
        print(high[['feature', 'target', 'NMI']].to_string())


if __name__ == '__main__':
    main()